repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5  # or specific git tag
    hooks:
      - id: script-must-not-have-extension
      - id: shellcheck
      - id: forbid-binary
  - repo: local
    hooks:
      - id: systemd-analyze
        name: systemd-analyze
        entry: systemd-analyze --no-pager verify systemd/nordvpn-netns.service
        files: 'systemd/nordvpn-netns.service'
        language: system
